In [1]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 68 kB 6.2 MB/s
  Building wheel for uuid (setup.py) ... done

In [2]:
import pandas as pd

In [5]:
df=pd.read_csv("adult .csv")

In [6]:
race_counts=df["race"].value_counts()

In [8]:
race_counts

White                 32924
Black                  3671
Asian-Pac-Islander     1171
Amer-Indian-Eskimo      374
Other                   323
Name: race, dtype: int64

In [9]:
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38459,42,Private,341757,Some-college,10,Never-married,Machine-op-inspct,Not-in-family,White,Female,0.0,0.0,40.0,United-States,<=50K
38460,36,Private,218542,HS-grad,9,Separated,Adm-clerical,Unmarried,Black,Female,0.0,0.0,40.0,United-States,<=50K
38461,44,Local-gov,190020,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
38462,27,Private,221436,Bachelors,13,Married-civ-spouse,Adm-clerical,Wife,White,Female,0.0,0.0,40.0,Cuba,>50K
38463,39,Self-emp-not-inc,52187,HS-grad,9,Married-civ-spouse,Exec-ma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
average_age_men=df[df["gender"]=="Male"]["age"].mean()

In [12]:
average_age_men

39.476209002840136

In [13]:
bachelors_percentage=(len(df[df["education"]=="Bachelors"])/len(df))*100

In [14]:
bachelors_percentage

16.524542429284526

In [15]:
educated_groups=[df[df["education"]=="Bachelors"],df[df["education"]=="Masters"],df[df["education"]=="Docatrate"]]

In [16]:
educated_groups

[       age         workclass  fnlwgt  education  educational-num  \
 11      36       Federal-gov  212465  Bachelors               13
 20      34           Private  107914  Bachelors               13
 23      25           Private  220931  Bachelors               13
 24      25           Private  205947  Bachelors               13
 32      24  Self-emp-not-inc  188274  Bachelors               13
 ...    ...               ...     ...        ...              ...
 38450   48           Private  344415  Bachelors               13
 38452   43           Private   27766  Bachelors               13
 38455   41           Private   22201  Bachelors               13
 38461   44         Local-gov  190020  Bachelors               13
 38462   27           Private  221436  Bachelors               13

               marital-status       occupation   relationship  \
 11        Married-civ-spouse     Adm-clerical        Husband
 20        Married-civ-spouse     Tech-support        Husband
 23             Never-married   Prof-specialty  Not-in-family
 24        Married-civ-spouse   Prof-specialty        Husband
 32             Never-married            Sales  Not-in-family
 ...                      ...              ...            ...
 38450  Married-spouse-absent   Prof-specialty  Not-in-family
 38452              Separated  Exec-managerial      Unmarried
 38455     Married-civ-spouse  Exec-managerial        Husband
 38461     Married-civ-spouse   Prof-specialty        Husband
 38462     Married-civ-spouse     Adm-clerical           Wife

                      race  gender  capital-gain  capital-loss  hours-per-week  \
 11                  White    Male           0.0           0.0            40.0
 20                  White    Male           0.0           0.0            47.0
 23                  White    Male           0.0           0.0            43.0
 24                  White    Male           0.0           0.0            40.0
 32                  White    Male           0.0           0.0            50.0
 ...                   ...     ...           ...           ...             ...
 38450               White    Male           0.0           0.0            37.0
 38452               White    Male           0.0           0.0            60.0
 38455  Asian-Pac-Islander    Male           0.0           0.0            40.0
 38461               White    Male           0.0           0.0            50.0
 38462               White  Female           0.0           0.0            40.0

       native-country income
 11     United-States  <=50K
 20     United-States   >50K
 23              Peru  <=50K
 24     United-States  <=50K
 32     United-States  <=50K
 ...              ...    ...
 38450  United-States   >50K
 38452  United-States   >50K
 38455          Japan   >50K
 38461  United-States  <=50K
 38462           Cuba   >50K

 [6356 rows x 15 columns],
        age         workclass  fnlwgt education  educational-num  \
 15      43           Private  346189   Masters               14
 40      65           Private  136384   Masters               14
 62      26           Private   31208   Masters               14
 89      41                 ?   38434   Masters               14
 92      33           Private  176410   Masters               14
 ...    ...               ...     ...       ...              ...
 38409   55  Self-emp-not-inc  157486   Masters               14
 38411   67                 ?   81761   Masters               14
 38422   39           Private  202937   Masters               14
 38434   57           Private  170287   Masters               14
 38456   35      Self-emp-inc  187046   Masters               14

            marital-status       occupation   relationship   race  gender  \
 15     Married-civ-spouse  Exec-managerial        Husband  White    Male
 40     Married-civ-spouse   Prof-specialty        Husband  White    Male
 62          Never-married  Exec-managerial  Not-in-family  White  Female
 89     Married-civ-spouse                ?           Wife  White  Female
 92     Married-civ-spouse   Prof-specialty           Wife  White  Female
 ...                   ...              ...            ...    ...     ...
 38409  Married-civ-spouse   Prof-specialty        Husband  White    Male
 38411  Married-civ-spouse                ?        Husband  White    Male
 38422       Never-married   Prof-specialty  Not-in-family  White  Female
 38434  Married-civ-spouse     Tech-support        Husband  White    Male
 38456  Married-civ-spouse     Adm-clerical        Husband  White    Male

        capital-gain  capital-loss  hours-per-week native-country income
 15              0.0           0.0            50.0  United-States   >50K
 40              0.0           0.0            50.0  United-States   >50K
 62              0.0           0.0            40.0  United-States  <=50K
 89           7688.0           0.0            10.0  United-States   >50K
 92           5178.0           0.0            10.0  United-States   >50K
 ...             ...           ...             ...            ...    ...
 38409        7298.0           0.0            40.0  United-States   >50K
 38411           0.0           0.0             2.0  United-States  <=50K
 38422           0.0           0.0            40.0  United-States   >50K
 38434           0.0           0.0            40.0  United-States   >50K
 38456           0.0           0.0            50.0  United-States  <=50K

 [2097 rows x 15 columns],
 Empty DataFrame
 Columns: [age, workclass, fnlwgt, education, educational-num, marital-status, occupation, relationship, race, gender, capital-gain, capital-loss, hours-per-week, native-country, income]
 Index: []]

In [17]:
educated_groups=pd.concat(educated_groups)

In [18]:
educated_groups

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
11,36,Federal-gov,212465,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K
20,34,Private,107914,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0.0,0.0,47.0,United-States,>50K
23,25,Private,220931,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Male,0.0,0.0,43.0,Peru,<=50K
24,25,Private,205947,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K
32,24,Self-emp-not-inc,188274,Bachelors,13,Never-married,Sales,Not-in-family,White,Male,0.0,0.0,50.0,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38409,55,Self-emp-not-inc,157486,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,7298.0,0.0,40.0,United-States,>50K
38411,67,?,81761,Masters,14,Married-civ-spouse,?,Husband,White,Male,0.0,0.0,2.0,United-States,<=50K
38422,39,Private,202937,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,0.0,0.0,40.0,United-States,>50K
38434,57,Private,170287,Masters,14,Married-civ-spouse,Tech-support,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
38456,35,Self-emp-inc,187046,Masters,14,Married-civ-spouse,Adm-clerical,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K

In [20]:
percentage_higher_education=(len(educated_groups[educated_groups["income"]==">50K"])/len(educated_groups))*100

In [21]:
round(percentage_higher_education,1)

44.4

In [23]:
uneducated_groups = df[df["education"] != "Bachelors"]
uneducated_groups = uneducated_groups[uneducated_groups["education"] != "Masters"]
uneducated_groups = uneducated_groups[uneducated_groups["education"] != "Doctorate"]

lower_education_rich = round ( (len( uneducated_groups[uneducated_groups["income"] == ">50K"]) / len(uneducated_groups)) * 100, 1)

In [24]:
uneducated_groups

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38457,22,Private,137591,Some-college,10,Never-married,Sales,Own-child,White,Male,0.0,0.0,35.0,United-States,<=50K
38458,53,Private,274276,HS-grad,9,Divorced,Adm-clerical,Not-in-family,White,Female,0.0,0.0,40.0,United-States,<=50K
38459,42,Private,341757,Some-college,10,Never-married,Machine-op-inspct,Not-in-family,White,Female,0.0,0.0,40.0,United-States,<=50K
38460,36,Private,218542,HS-grad,9,Separated,Adm-clerical,Unmarried,Black,Female,0.0,0.0,40.0,United-States,<=50K
38463,39,Self-emp-not-inc,52187,HS-grad,9,Married-civ-spouse,Exec-ma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df.education.value_counts()

HS-grad         12504
Some-college     8560
Bachelors        6356
Masters          2097
Assoc-voc        1622
11th             1438
Assoc-acdm       1236
10th             1095
7th-8th           745
Prof-school       627
9th               585
12th              496
Doctorate         457
5th-6th           396
1st-4th           187
Preschool          63
Name: education, dtype: int64

In [26]:
lowest_hrs=df["hours-per-week"].min()

In [27]:
lowest_hrs

1.0

In [28]:
slackers = df[df["hours-per-week"] == lowest_hrs]

In [29]:
percentage_wealthy_people=(len(slackers[slackers["income"]==">50K"])/len(slackers))*100

In [30]:
percentage_wealthy_people

14.285714285714285

In [32]:
wealth_percentages = (df[df["income"] == ">50K"]["native-country"].value_counts() / df["native-country"].value_counts())*100
wealth_percentages

?                             25.937031
Cambodia                      25.000000
Canada                        36.000000
China                         26.262626
Columbia                       6.250000
Cuba                          21.621622
Dominican-Republic             6.250000
Ecuador                       11.111111
El-Salvador                    6.250000
England                       38.679245
France                        42.307692
Germany                       27.160494
Greece                        39.024390
Guatemala                      1.449275
Haiti                         12.121212
Holand-Netherlands                  NaN
Honduras                      13.333333
Hong                          30.000000
Hungary                       28.571429
India                         41.284404
Iran                          34.000000
Ireland                       34.375000
Italy                         38.461538
Jamaica                       16.455696
Japan                         35.135135
Laos                                NaN
Mexico                         5.170068
Nicaragua                      8.108108
Outlying-US(Guam-USVI-etc)     5.882353
Peru                           9.090909
Philippines                   25.000000
Poland                        19.178082
Portugal                      20.000000
Puerto-Rico                   10.967742
Scotland                       5.882353
South                         19.780220
Taiwan                        43.137255
Thailand                      20.833333
Trinadad&Tobago                6.250000
United-States                 24.160588
Vietnam                        6.060606
Yugoslavia                    37.500000
Name: native-country, dtype: float64

In [33]:
highest_earning_country = wealth_percentages.idxmax()
highest_earning_country

'Taiwan'

In [34]:
highest_earning_country_percentage = round(wealth_percentages.max(), 1)
highest_earning_country_percentage

43.1

In [36]:
rich_indians = df[df["native-country"] == "India"]
rich_indians = rich_indians[rich_indians["income"] == ">50K"]
top_IN_occupation = rich_indians['occupation'].value_counts().idxmax()

In [37]:
rich_indians

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
1556,33,State-gov,150688,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,50.0,India,>50K
1890,45,Federal-gov,110884,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,Asian-Pac-Islander,Male,0.0,0.0,45.0,India,>50K
2359,53,Self-emp-not-inc,93449,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,40.0,India,>50K
2924,46,Self-emp-not-inc,135339,HS-grad,9,Married-spouse-absent,Craft-repair,Not-in-family,Asian-Pac-Islander,Male,0.0,0.0,45.0,India,>50K
3110,41,Federal-gov,350387,Masters,14,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,60.0,India,>50K
3401,63,Private,76286,Masters,14,Married-civ-spouse,Prof-specialty,Husband,Other,Male,0.0,0.0,40.0,India,>50K
4701,41,Self-emp-inc,56019,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,99999.0,0.0,50.0,India,>50K
4842,52,Self-emp-not-inc,98642,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,50.0,India,>50K
4854,39,Local-gov,123983,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0.0,0.0,40.0,India,>50K
5971,39,Private,79586,Some-college,10,Married-civ-spouse,Tech-support,Husband,Asian-Pac-Islander,Male,0.0,0.0,35.0,India,>50K
6229,47,State-gov,29023,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,40.0,India,>50K
6602,30,Private,164802,Bachelors,13,Never-married,Exec-managerial,Not-in-family,Other,Female,8614.0,0.0,40.0,India,>50K
8035,31,Private,124483,Masters,14,Never-married,Adm-clerical,Not-in-family,Asian-Pac-Islander,Male,0.0,0.0,60.0,India,>50K
8716,45,State-gov,255456,Masters,14,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,50.0,India,>50K
9821,33,Private,122749,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0.0,0.0,40.0,India,>50K
9920,40,Private,137421,Masters,14,Married-spouse-absent,Exec-managerial,Not-in-family,Asian-Pac-Islander,Male,0.0,0.0,35.0,India,>50K
11382,59,State-gov,139611,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,1977.0,40.0,India,>50K
12909,45,Private,92374,Some-college,10,Never-married,Exec-managerial,Not-in-family,Other,Male,13550.0,0.0,60.0,India,>50K
13374,46,Private,25894,Doctorate,16,Divorced,Prof-specialty,Not-in-family,Asian-Pac-Islander,Male,0.0,0.0,40.0,India,>50K
14405,43,Self-emp-inc,153205,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,70.0,India,>50K
14441,48,Private,355781,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,40.0,India,>50K
15606,53,Self-emp-inc,69372,Doctorate,16,Married-civ-spouse,Sales,Husband,Asian-Pac-Islander,Male,0.0,0.0,40.0,India,>50K
16292,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,40.0,India,>50K
17249,48,Private,164966,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0.0,0.0,40.0,India,>50K
17608,52,Private,168381,HS-grad,9,Widowed,Other-service,Unmarried,Asian-Pac-Islander,Female,0.0,0.0,40.0,India,>50K
23539,42,State-gov,102343,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,72.0,India,>50K
23566,54,State-gov,93449,Masters,14,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,40.0,India,>50K
24405,36,Private,172104,Prof-school,15,Never-married,Prof-specialty,Not-in-family,Other,Male,0.0,0.0,40.0,India,>50K
26220,43,Federal-gov,325706,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,50.0,India,>50K
26871,35,Private,98283,Prof-school,15,Never-married,Prof-specialty,Not-in-family,Asian-Pac-Islander,Male,0.0,0.0,40.0,India,>50K
26942,59,Private,122283,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,99999.0,0.0,40.0,India,>50K
27017,30,Private,243190,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,20.0,India,>50K
27541,54,Private,225599,Masters,14,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,7298.0,0.0,40.0,India,>50K
27665,34,Private,98283,Prof-school,15,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0.0,1564.0,40.0,India,>50K
29703,53,Private,366957,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,99999.0,0.0,50.0,India,>50K
29832,40,Private,220977,Doctorate,16,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,3103.0,0.0,40.0,India,>50K
30143,45,Private,209912,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0.0,0.0,40.0,India,>50K
32298,41,Private,207578,Assoc-acdm,12,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0.0,0.0,50.0,India,>50K
33059,43,Private,242968,Masters,14,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0.0,0.0,40.0,India,>50K
33204,41,Private,143003,Assoc-voc,11,Married-civ-spouse,Other-service,Husband,Asian-Pac-Islander,Male,7298.0,0.0,60.0,India,>50K
33540,57,Self-emp-inc,123053,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,15024.0,0.0,50.0,India,>50K
34115,29,Self-emp-not-inc,341672,HS-grad,9,Married-spouse-absent,Transport-moving,Other-relative,Asian-Pac-Islander,Male,0.0,1564.0,50.0,India,>50K
36698,42,Self-emp-inc,23510,Masters,14,Divorced,Exec-managerial,Unmarried,Asian-Pac-Islander,Male,0.0,2201.0,60.0,India,>50K
36746,39,Private,198654,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,2415.0,67.0,India,>50K
37409,30,Private,122889,Masters,14,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,50.0,India,>50K

In [38]:
top_IN_occupation

'Prof-specialty'